# Use official PHP FPM image
FROM php:8.2-fpm

# Install OS dependencies & PHP extensions
RUN apt-get update && apt-get install -y \
    zip unzip curl libpng-dev libjpeg-dev libfreetype6-dev libonig-dev libxml2-dev \
    supervisor \
    && docker-php-ext-install pdo_mysql mbstring exif pcntl bcmath gd

# Install and enable phpredis extension
RUN pecl install redis && docker-php-ext-enable redis

# Copy Composer binary from official Composer image
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

# Copy Supervisor config for production
COPY docker/php/supervisord.prod.conf /etc/supervisor/conf.d/supervisord.conf

# Set working directory
WORKDIR /var/www/html

# Copy Laravel app
COPY ./laravel-app /var/www/html

# Install only production PHP dependencies
RUN composer install --no-dev --optimize-autoloader && \
    chown -R www-data:www-data /var/www/html

# Start Supervisor to manage PHP-FPM + Laravel queue
CMD ["/usr/bin/supervisord"]